version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"   # Next.js UI
      - "4001:4001"   # Go backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: billing
      DB_PORT: 5432
      TB_URI: https://dashboard.lumenenergysolutions.com/api 
      TB_BILLING_ID: ce0482e0-5425-11ef-aa15-a127638e3a77 
      TB_USERNAME: <username>
      TB_PASSWORD: <password>
volumes:
  pgdata: